AWSTemplateFormatVersion: "2010-09-09"
Description: "Roles for CI stack"

Parameters:
  ServiceName:
    Type: String
    Description: The name of the service
  OutBucket:
    Type: String
    Description: Name of the output bucket
  ArtifactBucket:
    Type: String
    Description: Name of the artifact bucket

Outputs:
  RoleArn:
    Description: The build role for CI
    Value: !GetAtt BuildServiceRole.Arn

Resources:
  BuildServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        # View everything
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
        # This gives permission to create logs
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub ${ServiceName}-BucketPermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "s3:*"
                Resource:
                  - !Sub "arn:aws:s3:::${OutBucket}"
                  - !Sub "arn:aws:s3:::${OutBucket}/*"
                  - !Sub "arn:aws:s3:::${ArtifactBucket}"
                  - !Sub "arn:aws:s3:::${ArtifactBucket}/*"
